#!/usr/bin/env python3


import os
import sys

try:
    import pexpect
except ImportError:
    print('Required library "pexpect" not exists. Install with pip and try again')
    sys.exit(1)

_COMMAND_ = './Client-Publish-Map.py --Ice.Config=Server.config "%(map_proxy)s" "%(token)s" "%(archivo)s"'

try:
    proxy, token, archivo = sys.argv[1:]
except ValueError:
    print('Command arguments: {} <map_proxy> <token> <archivo>'.format(
        os.path.basename(sys.argv[0]))
    )
    sys.exit(1)

# Compose command
final_command = _COMMAND_ % {
    'map_proxy': proxy,
    'token': token,
    'archivo': archivo
}
proc = pexpect.spawn(final_command, echo=False)
proc.expect([''])
print(proc.before.decode().strip())
